dependencies = {
	layers:  [
		{
		name: "pion-dojo.js",
		dependencies: [
			"dojo.parser",
			"dojo.data.ItemFileReadStore",
			"dojo.data.ItemFileWriteStore",
			"dojo.dnd.move",
			"dojo.dnd.Source",
			"dijit.Dialog",
			"dijit.form.FilteringSelect",
			"dijit.form.Form",
			"dijit.form.TextBox",
			"dijit.form.Textarea",
			"dijit.form.ValidationTextBox",
			"dijit.form.Button",
			"dijit.form.CheckBox",
			"dijit.layout.ContentPane",
			"dijit.layout.BorderContainer",
			"dijit.layout.LayoutContainer",
			"dijit.layout.AccordionContainer",
			"dijit.layout.StackContainer",
			"dijit.layout.SplitContainer",
			"dijit.layout.TabContainer",
			"dijit.Menu",
			"dijit.Tree",
			"dojox.data.XmlStore",
			"dojox.gfx",
			"dojox.grid.Grid",
			"dojox.grid.editors",
			"dojox.grid._data.model",
			"dojox.grid._data.dijitEditors",
			"dojox.xml.DomParser",
			"dojox.dtl.filter.strings",
			"dojox.dtl.filter.htmlstrings",
			"pion.pion",
			"pion.login",
			"pion.terms",
			"pion.reactors",
			"pion.vocabularies",
			"pion.codecs",
			"pion.databases",
			"pion.users",
			"pion.system",
			"pion.widgets.User",
			"plugins.reactors.Reactor",
			"plugins.codecs.Codec",
			"plugins.databases.Database",
			"plugins.vocabularies.Vocabulary",
		]
		}
	],
	prefixes: [
		[ "dijit", "../dijit" ],
		[ "dojox", "../dojox" ],
		[ "pion", "C:/pion-platform/platform/ui/scripts" ],
		[ "plugins", "C:/pion-platform/platform/ui/plugins" ],
		[ "resources", "C:/pion-platform/platform/ui/resources" ]
	]
};
